name: BSB Auto-update

on:
  push:
    branches: [master]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: splitpayments/bsb-au-updater-action@master
    - name: Debug URLS
      run: cat urls
    - name: Set up Ruby 2.6
      uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6.x
    - name: Update JSON
      run: |
        gem install bundler
        bundle install
        bundle exec rake bsb:generate_bank_list url=$BSB_KEY_URL > config/bsb_bank_list.json
        bundle exec rake bsb:generate_database filename=$FULL_LIST_PATHNAME > config/bsb_db.json
    - name: Commit
      env:
        GITHUB_TOKEN: ${{ secrets.TOKEN }}
      run: |
        rm urls
        test $(hub status --porcelain | wc -l) -gt 0 && \
        hub add --all && \
        hub commit --message="Update BSB data" && \
        hub push
